# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TinderDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TinderDemo
  pod 'TinderSwipeView'
  pod 'Alamofire'
  pod 'KDCalendar'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'SwiftyJSON'

  target 'TinderDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TinderDemoUITests' do
    # Pods for testing
  end

end
